version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - storage:/var/www/storage
    networks:
      - laravel-network
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - storage:/var/www/storage:ro
    depends_on:
      - app
    networks:
      - laravel-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network
    restart: unless-stopped

networks:
  laravel-network:
    driver: bridge

volumes:
  storage:
    driver: local
  mysql_data:
    driver: local