- uses: actions/checkout@v3

- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: "8.3"
    extensions: mbstring, dom, fileinfo, mysql
    coverage: xdebug

- name: Copy .env
  run: php -r "file_exists('.env') || copy('.env.example', '.env');"

- name: Wait for MySQL
  run: |
    until mysqladmin ping -h127.0.0.1 -uroot -ppassword --silent; do
      echo "Waiting for database connection..."
      sleep 5
    done

- name: Install Dependencies
  run: composer install ...

- name: Generate Key
  run: php artisan key:generate
  env:
    DB_CONNECTION: mysql
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_DATABASE: testing
    DB_USERNAME: root
    DB_PASSWORD: password

- name: Directory Permissions
  run: chmod -R 777 storage bootstrap/cache

- name: Run Tests
  run: php artisan test
