name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, mysql, gd, bcmath, redis
        tools: composer:v2

    - name: Copy .env
      run: |
        cp .env.example .env
        sed -i 's/DB_HOST=.*/DB_HOST=mysql/' .env
        sed -i 's/REDIS_HOST=.*/REDIS_HOST=redis/' .env
        cat .env

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Generate Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

  build-and-deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Install dependencies
      run: composer install --no-dev --no-interaction --optimize-autoloader --no-plugins

    - name: Build and push Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        DOCKER_BUILDKIT=1 docker build \
          --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/cdk-trenggalek:latest \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/cdk-trenggalek:${{ github.sha }} .

        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cdk-trenggalek:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cdk-trenggalek:${{ github.sha }}

    - name: SSH and deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/kda/cdk-trenggalek
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
          docker-compose exec app composer install --no-interaction --optimize-autoloader --no-dev
          docker-compose exec app php artisan migrate --force
          docker-compose exec app php artisan cache:clear
          docker-compose exec app php artisan view:clear