name: Laravel

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Setup MySQL
      run: |
            sudo systemctl start mysql
            sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
            sudo mysql -e "CREATE DATABASE IF NOT EXISTS testing_database;"
            sudo mysql -e "CREATE USER IF NOT EXISTS 'tester'@'localhost' IDENTIFIED BY 'password';"
            sudo mysql -e "GRANT ALL PRIVILEGES ON testing_database.* TO 'tester'@'localhost';"
            sudo mysql -e "FLUSH PRIVILEGES;"
    - name: Execute tests (Unit and Feature tests) via Pest
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: db_cdk_trenggalek
        DB_USERNAME: root
        DB_PASSWORD: password
        DB_HOST: 127.0.0.1
      run: ./vendor/bin/pest
